// function isPalindrome(s) {
//   let l = 0
//   let r = s.length - 1

//   while(l < r) {
//     if (s[l] !== s[r]) {
//       return false
//     }

//     l++
//     r--
//   }

//   return true
// }

// var validPalindrome = function(s) {
//   if (!isPalindrome(s)) {
//     const sarr = s.split('')
//     for(let i = 0; i < sarr.length; i++) {
//       const curArr = Array.from(sarr)
//       curArr.splice(i, 1)
//       if (isPalindrome(curArr.join(''))) {
//         return true
//       }
//     }

//     return false
//   } else {
//     return true
//   }

// }

function isPalindrome(s, l, r) {
  while(l < r) {
    if (s[l] !== s[r]) {
      return false
    }

    l++
    r--
  }

  return true
}

var validPalindrome = function(s) {
  let l = 0
  let r = s.length - 1

  if (isPalindrome(s, l, r)) {
    return true
  }
  
  while(l < r) {
    if (s[l] != s[r]) {
      return isPalindrome(s, l, r - 1) || isPalindrome(s, l + 1, r)
    }
    l++
    r--
  }

  return false
}

// const s = 'abca'

const s = 'abbcdca'
// const s = "chldgwrinywkcbkgevaorfndrjysvcpbqmybztrdrpszyjjffinpkfzakqvkvxxiqjcjpcnbhaqxdgcoqoajpwqftvnmnjcltisocufjpqquvfnlylyrbvfhjxqungoedsmhrooxijmxcxatyrymiqimpmrsbkvzaomztdwaahwyesgefgbdqhbvdsmfxmypcejjvhjbiitbrqjcmqiavrueshuhqgzucgmgsbconklortytyzlkhgfmmdejqnczhhgpwlcduawgignknohjqxklzzgunanhadatukgcxadesddtjoqzwgzuuqaixxecomzoxhdpsxbcqecliopvcrczeivmpsvfeimioddzbaaryytesuaovdwdordwdfznjzslgqtlfnavyftvzbttwpgrlhoxtjvgfncurlgecyhiabvrkcwhhhfoatvbwmuhvdsnizuebhnxwjdrlodbrammekzjxzjfmxnolfmdodlnofdghfhuanflokwgjxbfeqhohayfeklhbmmtbtccjpqptxvizrbpgmiyuszwrfkgvhflvfdbybdwpxikllwrwdkddbtegdlixzpytikaifysuqyhjkvqrrlzkzrcxpqekbbpvvxzeolxezfxkkdlrfxpefvqpbitnwscznbbhmomuskoepjooufuseajzsnonfiztorltmibzevtcrpioalvhhpejdilcvnsetuavhbsynwevbttbjxuicsyfplhaasljapjdwzcvbujlshllhndykmaywnbrqdvzggmmlsjknssgkbfcjdigcrrmjjattybkrmqjmuucvhmmokvsnlqujhlopfsxumefurorjvbghjbktymltlyuzgvfblcifitinsappdrmrtmdwxfjrulobkzeypnftmwnqiaehlkgcrifeedjdbprqjypbfoywybyolnfavsbfdmwmygrylwsbqppltqwbphbvingxpiwrhxyzwckmzezzjwnlcurdowgtweijdyongmrzgtmujvkumvtdblmjylbsbszklnhiwujrbsijtsttfjwsmxutftcndwwpwgtsawthigorubpkmtjyuslhfhlkhlqwzrkvcqicamphwfmebszddnbxuyyxymzfurxwgzxxusgvtezimbbkodytipcagglworeeandoksrgvyxuysgmckymmgncrsxkplgxipssylgajezprqthcjrrljydfxjgzjdfkvpdpbpyesjzscmmnzycbuymztuqoybolgefzahctltgauwnfarxwkqnjczfouywouvzfxjhpxryviuiciqxwvhsnjeijuuqgkdeyllrxcazpgeiaxuxxzgdefdfkyzooeptrsyyobtcysnxzzdhmtbxqtsrkcfxcsackjxzhbhkdbzlydkgyyezrydcizozhhqszkysspoogdnqicparafirmseprtnubdxqqemnaaocqzzpehjwshdnpppsbgpgjqzcuhszmbhcadnrwcdgnuekpofqixfxymdcnavctwctthhggrumpftuwkkngnwzdzboizsyyxhzrvahenbxpidfhdomqndwwzzjskuexbvwykdwrxismycrsyybpsvgxwrkukmvdtdujrihjksaqjndckoexpmodbbqciysjfbsckjydrtlttkwguozqakhuotfdrpwpgvjffpkudimqpafvftxyssintybrbvyxinnukermehkvoeyfvkqimwbbmktspvseybwwhldyuqyadxfxtxcgixweekjxhhzmqyqlajegpbvjektwyiarnculchdvpufyrldnlypetaocwucprhwxjpcbquqwbohxdjminuftjhrwiliimtfhgbygmaojipqjzdhqqipsjcaaqymindstdhwggwxaedbrdbliqwtwgdurnnplbhhtopcyrziympeytmapofqvcxzjrbsmxcuexmjabwwsrfjwygcvtcsidmobekzidzelbtyrdnbxmgpnqetvojfocllycumqciaetqsdpmxgpdobfwtezqlqadfvowgvymvraemqnsfstwfqoqszrerkrxdeyplbdrbgquzordfvhaqrynepexhrzpxswxjryjrpuooxbxvxzldviufxjhfvvjgprdjzpntbiwwovwjkzlqzyfgqouodzqghtbpibiwkxuzdupkuednigbxygbzwcgutglsukjxayedwrusrztfocrmlnovgwshhaafqduylkldddxvqrbuueluzbbejwwexcbwaqhsbwdpmynbyfgxlmbflvunereoaluywyvxfophfnpvwssrlfzwbuvzddmlenwdqjjmvwzqbhajvccdxwrrvcdyaxlrfvbcdsnrsdrcjzmppkgtqtuczcaktbfowqvemvoroqohtpzutqnetbzcsdeasaiijtaydfomowrttyvrxfacgregopsjbqdwtnmuywfilqdweargjbfmevivmgpzxqqbddqrobrylmtmtfhvsahyewqfwsioawzvgkqetqblcxbrdjpvffqyxoajdnchlxumldgnjwflprelijekppnppfiwldyezysjvsnxeebkubouujvgiabmlsbltdpaupuswxieopgumhoavyjvtmrhumuazzkrblojtifnandzxnmklfngsnuckyjllilpwjrpkaoxytbpafwppwlsmfvqdfxspkxrciluzzppcpsjyccnmabmujmnvdunniqfkuhkkxjspfsyuvfcumuurkemfgzndnqugodmuyzkphootwhevutaldqgcgenrkjmymghbifrgeyyjxxwmmcdzxlkbrurvkzmsuyuilwoukoowcdzxppywwbjqclmpkncbegqoksycglpeihizctmjrnamyotlvudqjzicintashtgcblgbmarjuncklxxwuatulgeawlihfpdgjaexwsokdboagwynjjfridcfgbvvvubmdxuqbkrwkojanzlwzhdghviczesjnttqexguuutthsrhafgigxgvigvmovsedrzzlmemxhjthojufmjsocqdcqxpdbflyyylknoxsoqutxhbabjxnagczqyouxfpuskwvbapfboozjztbazytehetiokydygdpovnxhukdqexjfvzsvcnhkimtmamsseiabxoeaijpzhymkkgudjrhvhzxyecltvhrmlvigopcsmgidvwjriwscltnzjetrbbaakzwecuzajbiwgsroficxjwoblergzyhjcvexbeckeaghlwirtuatokdqtntovjgdditbgmoxgqfqhfcqgyvvdunifrmviefwzqupahjcxvdposecoonilxcccmljtfhqmvdgjovxnbkoudraakjcncetvwxoierhkydnjrdwuzmbqcveoexvcqbpatopwtiqkexpfpeqgoudkfijypagsemnxpfjpajlzawzwqonnorhzryxiexgzicgyrwhdkrbzbhdxdgjyndhofptpajranfkempyigcxbzmmhqrohgghnayumbmbmtfdrxsmxtqvtbzhmolqgctuixkdhiquowjizucsxgoczlqopdzlvfqrpyqzylrdnaishwrdgukttikbbclhaceizncbirggmxvwizeeyvdgtjfhazzbayerfexeplgysuqckcrswumhksuciyqniytznjhzpapbuuicgavpqwyugayojcikqfmbetxvctnutkjmglbwfnieqewqwfeopmxwnpeplbmfgkmesjngipnepzhtixmdzglgwfqjvoawadybcejyqxseazpzoddudcvzlaqjhlyysnycborlgdlrnivvevhyujowhyxfuvrlrenartwnhppbcwjzbwpdrqbybtpalgsyovoidnwdjovoxpwjlbsuhjnrzznatspoyyyotgqwdxbfrkeepffrwrtimdttkdqqqcydgznnrdjkwsedwyusudwarnnlueyepirvucuopgsgyxleebiebsrgpysjvqpdjvnwwnphnoixglunkjdhzhsbffdltwmvpmntzvxokgzttwyszlmmzjeqwvrzbbokyuoxnunztgdtjuhimfbmfcnormiqmadrnsoxkxjkuqniwczcogvtyixpcdbrkbbpubuqixnbuiawvjactjtqseowhxwfgcbrfapcjhbemlohtfhmuqevdssctjkbsvovtmvytcxywsdpwrehatbzeggqgibgxmufdeflnbgjgxbgksbuifquxqhvyirqyrkghkvhdpsmujejyzvqrmmbxurtlmimtalseikyqusaonfmkvzccguhvpzpqvxxminswqbufmlxekhvfgenuxbygsalafgchivxteebnkdxafnekphqhbawdtohtlrqmsgfwltpnqwabnnxcgcvpddhgpdjemfhastlyvzcbpxlizqinijxntpvsgigpmxerdtcgljiqgnuihujsthtulbmhvqkoigvnqtkosvsvdwfyyqvpcxtoiiahpyvbwmrmfnrbcmdokrlttqaysdwfdlhvuoshwapsgqopnutazswqzrdwwkzeoegmbusyogplyfwxxsxpannsctymckbspmrkxpitsxxdyeqcjkiqpsgsmxmoidcipzpjwetzmvxnvwnqsoabstfvqwbgzpuegcmrucydgkyrcyezezjwchjybvdrfxqgteillressopdpdgxjsbkachvxqmrxxaoihdpkaxlxdhqhiudhglbnscczldgqigffoctsjwvdotwrrnoxprzppactmlkjxclysavtgyrlidhhbxwbratvhfhtzwsrbejniodeassnlallhqtpuobhmhemvgjrmtsdewppsrjmqibnmwwuqvfwdplchuvecbvgfsquemqrokiwungjainmizxgijlldnjwcjlkunyloiingepyxtbwzagreeegkbumgahnipfwkddkwfpinhagmubkgeeergazwbtxypegniiolynukljcwjndlljigxzimniajgnuwikorqmeuqsfgvbcevuhclpdwfvquwwmnbiqmjrsppwedstmrjgvmehmhbouptqhllalnssaedoinjebrswzthfhvtarbwxbhhdilrygtvasylcxjklmtcappzrpxonrrwtodvwjstcoffgiqgdlzccsnblghduihqhdxlxakpdhioaxxrmqxvhcakbsjxgdpdposserllietgqxfrdvbyjhcwjzezeycrykgdycurmcgeupzgbwqvftsbaosqnwvnxvmztewjpzpicdiomxmsgspqikjcqeydxxstipxkrmpsbkcmytcsnnapxsxxwfylpgoysubmgeoezkwwdrzqwszatunpoqgspawhsouvhldfwdsyaqttlrkodmcbrnfmrmwbvyphaiiotxcpvqyyfwdvsvsoktqnvgiokqvhmbluthtsjuhiungqijlgctdrexmpgigsvptnxjiniqzilxpbczvyltsahfmejdpghddpvcgcxnnbawqnptlwfgsmqrlthotdwabhqhpkenfaxdknbeetxvihcgfalasgybxunegfvhkexlmfubqwsnimxxvqpzpvhugcczvkmfnoasuqykieslatmimltruxbmmrqvzyjejumspdhvkhgkryqriyvhqxuqfiubskgbxgjgbnlfedfumxgbigqggezbtaherwpdswyxctyvmtvovsbkjtcssdvequmhftholmebhjcpafrbcgfwxhwoesqtjtcajvwaiubnxiqubupbbkrbdcpxiytvgoczcwinqukjxkxosnrdamqimroncfmbfmihujtdgtznunxouykobbzrvwqejzmmlzsywttzgkoxvztnmpvmwtldffbshzhdjknulgxionhpnwwnvjdpqvjsypgrsbeibeelxygsgpoucuvripeyeulnnrawdusuywdeswkjdrnnzgdycqqqdkttdmitrwrffpeekrfbxdwqgtoyyyopstanzzrnjhusbljwpxovojdwndiovoysglaptbybqrdpwbzjwcbpphnwtranerlrvufxyhwojuyhvevvinrldglrobcynsyylhjqalzvcduddozpzaesxqyjecbydawaovjqfwglgzdmxithzpenpignjsemkgfmblpepnwxmpoefwqweqeinfwblgmjktuntcvxtebmfqkicjoyaguywqpvagciuubpapzhjnztyinqyicuskhmuwsrckcqusyglpexefreyabzzahfjtgdvyeeziwvxmggribcnziecahlcbbkittkugdrwhsiandrlyzqyprqfvlzdpoqlzcogxscuzijwouqihdkxiutcgqlomhzbtvqtxmsxrdftmbmbmuyanhgghorqhmmzbxcgiypmekfnarjaptpfohdnyjgdxdhbzbrkdhwrygcizgxeixyrzhronnoqwzwazljapjfpxnmesgapyjifkduogqepfpxekqitwpotapbqcvxeoevcqbmzuwdrjndykhreioxwvtecncjkaarduokbnxvojgdvmqhftjlmcccxlinoocesopdvxcjhapuqzwfeivmrfinudvvygqcfhqfqgxomgbtiddgjvotntqdkotautriwlhgaekcebxevcjhyzgrelbowjxciforsgwibjazucewzkaabbrtejzntlcswirjwvdigmscpogivlmrhvtlceyxzhvhrjdugkkmyhzpjiaeoxbaiessmamtmikhncvszvfjxeqdkuhxnvopdgydykoitehetyzabtzjzoobfpabvwksupfxuoyqzcganxjbabhxtuqosxonklyyylfbdpxqcdqcosjmfujohtjhxmemlzzrdesvomvgivgxgigfahrshttuuugxeqttnjsezcivhgdhzwlznajokwrkbquxdmbuvvvbgfcdirfjjnywgaobdkoswxeajgdpfhilwaeglutauwxxlkcnujrambglbcgthsatnicizjqduvltoymanrjmtczihieplgcyskoqgebcnkpmlcqjbwwyppxzdcwookuowliuyusmzkvrurbklxzdcmmwxxjyyegrfibhgmymjkrnegcgqdlatuvehwtoohpkzyumdoguqndnzgfmekruumucfvuysfpsjxkkhukfqinnudvnmjumbamnccyjspcppzzulicrxkpsxfdqvfmslwppwfapbtyxoakprjwplilljykcunsgnflkmnxzdnanfitjolbrkzzaumuhrmtvjyvaohmugpoeixwsupuapdtlbslmbaigvjuuobukbeexnsvjsyzeydlwifppnppkejilerplfwjngdlmuxlhcndjaoxyqffvpjdrbxclbqteqkgvzwaoiswfqweyhasvhftmtmlyrborqddbqqxzpgmvivemfbjgraewdqlifwyumntwdqbjspogergcafxrvyttrwomofdyatjiiasaedsczbtenqtuzpthoqorovmevqwofbtkaczcutqtgkppmzjcrdsrnsdcbvfrlxaydcvrrwxdccvjahbqzwvmjjqdwnelmddzvubwzflrsswvpnfhpofxvywyulaoerenuvlfbmlxgfybnympdwbshqawbcxewwjebbzuleuubrqvxdddlklyudqfaahhswgvonlmrcoftzrsurwdeyaxjkuslgtugcwzbgyxbgindeukpudzuxkwibipbthgqzdouoqgfyzqlzkjwvowwibtnpzjdrpgjvvfhjxfuivdlzxvxbxoouprjyrjxwsxpzrhxepenyrqahvfdrozuqgbrdblpyedxrkrerzsqoqfwtsfsnqmearvmyvgwovfdaqlqzetwfbodpgxmpdsqteaicqmucyllcofjovteqnpgmxbndrytblezdizkebomdisctvcgywjfrswwbajmxeucxmsbrjzxcvqfopamtyepmyizrycpothhblpnnrudgwtwqilbdrbdeaxwggwhdtsdnimyqaacjspiqqhdzjqpijoamgybghftmiiliwrhjtfunimjdxhobwquqbcpjxwhrpcuwcoatepylndlryfupvdhclucnraiywtkejvbpgejalqyqmzhhxjkeewxigcxtxfxdayquydlhwwbyesvpstkmbbwmiqkvfyeovkhemrekunnixyvbrbytnissyxtfvfapqmidukpffjvgpwprdftouhkaqzougwkttltrdyjkcsbfjsyicqbbdompxeokcdnjqaskjhirjudtdvmkukrwxgvspbyysrcymsixrwdkywvbxeuksjzzwwdnqmodhfdipxbnehavrzhxyysziobzdzwngnkkwutfpmurgghhttcwtcvancdmyxfxiqfopkeungdcwrndachbmzshuczqjgpgbspppndhswjhepzzqcoaanmeqqxdbuntrpesmrifarapciqndgoopssykzsqhhzozicdyrzeyygkdylzbdkhbhzxjkcascxfckrstqxbtmhdzzxnsyctboyysrtpeoozykfdfedgzxxuxaiegpzacxrllyedkgquujiejnshvwxqiciuivyrxphjxfzvuowyuofzcjnqkwxrafnwuagtltchazfeglobyoqutzmyubcyznmmcszjseypbpdpvkfdjzgjxfdyjlrrjchtqrpzejaglysspixglpkxsrcngmmykcmgsyuxyvgrskodnaeerowlggacpitydokbbmizetvgsuxxzgwxrufzmyxyyuxbnddzsbemfwhpmaciqcvkrzwqlhklhfhlsuyjtmkpburogihtwastgwpwwdnctftuxmswjfttstjisbrjuwihnlkzsbsblyjmlbdtvmukvjumtgzrmgnoydjiewtgwodruclnwjzzezmkcwzyxhrwipxgnivbhpbwqtlppqbswlyrgymwmdfbsvafnloybywyofbpyjqrpbdjdeefircgklheaiqnwmtfnpyezkbolurjfxwdmtrmrdppasnitificlbfvgzuyltlmytkbjhgbvjrorufemuxsfpolhjuqlnsvkommhvcuumjqmrkbyttajjmrrcgidjcfbkgssnkjslmmggzvdqrbnwyamkydnhllhsljubvczwdjpajlsaahlpfysciuxjbttbvewnysbhvautesnvclidjephhvlaoiprctvezbimtlrotzifnonszjaesufuoojpeoksumomhbbnzcswntibpqvfepxfrldkkxfzexloezxvvpbbkeqpxcrzkzlrrqvkjhyqusyfiakitypzxildgetbddkdwrwllkixpwdbybdfvlfhvgkfrwzsuyimgpbrzivxtpqpjcctbtmmbhlkefyahohqefbxjgwkolfnauhfhgdfonldodmflonxmfjzxjzkemmarbdolrdjwxnhbeuzinsdvhumwbvtaofhhhwckrvbaihyceglrucnfgvjtxohlrgpwttbzvtfyvanfltqglszjnzfdwdrodwdvoausetyyraabzddoimiefvspmviezcrcvpoilceqcbxspdhxozmocexxiaquuzgwzqojtddsedaxcgkutadahnanugzzlkxqjhonkngigwaudclwpghhzcnqjedmmfghklzytytrolknocbsgmgcuzgqhuhseurvaiqmcjqrbtiibjhvjjecpymxfmsdvbhqdbgfegseywhaawdtzmoazvkbsrmpmiqimyrytaxcxmjixoorhmsdeognuqxjhfvbrylylnfvuqqpjfucositlcjnmnvtfqwpjaoqocgdxqahbncpjcjqixxvkvqkazfkpniffjjyzsprdrtzbymqbpcvsyjrdnfroavegkbckwynirwgdlhcb"
console.log(validPalindrome(s))